### ISSUE TITLE
Can't import ScreenClass or ScreenBadge

### ISSUE THREAD

**Issue by nbamfordcirium** [santosfrancisco/react-awesome-styled-grid#137]
Using version 3.1.0, I find the util object is exported, but attempting to import ScreenClass or ScreenBadge yields `Module '"react-awesome-styled-grid"' has no exported member 'ScreenClass'.`

**Comment by santosfrancisco** [comment]
@nbamfordcirium Good catch! Are you using this library in a typescript project? I will add the types of ScreenClass and ScreenBadge. Thanks for reporting!

**Comment by nbamfordcirium** [comment]
Thanks for the fast turnaround! We are using the grid with typescript, and we love it-- it's a terrific project. I should have led with that :-)

**Comment by nbamfordcirium** [comment]
I note there's still an issue with `ScreenBadge`. It's defined as a `StyledComponent`, which isn't imported into `types/index.d.ts`. I added that import from `styled-components`, but that yielded: `node_modules/react-awesome-styled-grid/types/index.d.ts:109:27 - error TS2707: Generic type 'StyledComponent' requires between 2 and 4 type arguments.`

It looks like `AnyStyledComponent` would work, but I'm far from an expert on `styled-components`. 

Thanks again!
