### ISSUE TITLE
ScreenBadge styled-components type doesn't seem quite right

### ISSUE THREAD

**Issue by nbamfordcirium** [santosfrancisco/react-awesome-styled-grid#140]
Hi, I mentioned this in a comment to a closed issue, so I figured I would reproduce it here, I hope I'm not spamming you ;-)

I note there's still a typescript issue with ScreenBadge. It's defined as a `StyledComponent`, which isn't imported into `types/index.d.ts`. I added that import from styled-components, but that yielded: `node_modules/react-awesome-styled-grid/types/index.d.ts:109:27 - error TS2707: Generic type 'StyledComponent' requires between 2 and 4 type arguments`.

It looks like `AnyStyledComponent` would work, but I'm far from an expert on styled-components.

**Comment by santosfrancisco** [comment]
Done! Please check version 3.1.4 🚀  Thanks!
