### ISSUE TITLE
Fails to pass other props.Only passes the classNames and children

### ISSUE THREAD

**Issue by mainanick** [santosfrancisco/react-awesome-styled-grid#47]
https://github.com/santosfrancisco/react-awesome-styled-grid/blob/2022477b07a3d912f2f32f73300b7ad3b7b9f9b3/src/components/grid/col.js#L6-L8

Should Instead be 
```jsx
   const Col = styled.div``

**Comment by mainanick** [comment]
@santosfrancisco Any reviews?

**Comment by santosfrancisco** [comment]
Sorry for the delay @mainanick . Revised and approved! Thanks for the contribution.
