### ISSUE TITLE
Typescript types

### ISSUE THREAD

**Issue by diegoarcega** [santosfrancisco/react-awesome-styled-grid#62]
Hey dudes, I love this lib but I noticed there's no typescript types defined and my linter is complaining. Is there any task in the horizon to add types to this project or have a @types/ helper?

**Comment by santosfrancisco** [comment]
Hello @diegoarcega , how are you? Glad to use our lib, thank you very much! Unfortunately I haven't the typscript knowledge to develop this feature. You have no interest in contributing to this? It would be very welcome!

**Comment by diegoarcega** [comment]
thanks @santosfrancisco , yes I'd like to do this. 
Maybe I will add them little by little, seems to much to be done at once.

**Comment by ixahmedxi** [comment]
@diegoarcega I am interested in also providing typescript types for this project, we could do it together if you're interested.

**Comment by diegoarcega** [comment]
@ixahmedxi yes I am, I've just started a new job now I might not be so available for it though. But if you kick it off we can take it from there.

**Comment by ixahmedxi** [comment]
@diegoarcega I have already worked on it for a bit and finished the props types for the Container, Row and Col components so if you want to add some types whenever you are free here's the link of the types file just pull it and commit your changes to the typescript-types branch. :)

[The typescript-types branch](https://github.com/ixahmedxi/react-awesome-styled-grid/blob/typescript-types)

**Comment by ixahmedxi** [comment]
Alright then will do!

**Comment by santosfrancisco** [comment]
merged! :smiley: Thanks @ixahmedxi and @diegoarcega
