### ISSUE TITLE
Internet Explorer 11 misses polyfill for scrollTo

### ISSUE THREAD

**Issue by eimerreis** [santosfrancisco/react-awesome-styled-grid#91]
Hi There,

don't know if this just related to your demo website or to the whole package, but when trying to open your demo site on IE11 (yep - I really need to support IE11 😆 ), an error occurs because scrollTo is not implemented.

![image](https://user-images.githubusercontent.com/14016944/74818063-43bf4200-52fe-11ea-837e-a11984593daa.png)

Maybe you'll need to add https://github.com/iamdustan/smoothscroll as a peer dependency.

I will test the library using IE11 and keep you updated, but maybe you already know that IE11 won't be possible to support using this lib.

**Comment by santosfrancisco** [comment]
Hello @eimerreis thanks for use this library :heart: ! I think that problem with `scrollTo` is related with Docz ([docz.site](https://docz.site)) which is the tool used to create this documentation. I will see the new releases and update if needed. Perhaps this has been solved.

Please, keep me updated about the tests using IE11. Thank you!

**Comment by aldenfbrown** [comment]
Hello Francisco,

I have confirmed two items in regards to react-awesome-styled-grid in IE11.

1. The documentation site: The scrollTo breaks and prevents the documention site from fully loading. 

2. Local build: The grid and columns render and behave as expected in IE11.

BTW, I really dig this package! Thank you!!
Alden
