### ISSUE TITLE
Usage examples don't work as shown

### ISSUE THREAD

**Issue by DJmRek** [santosfrancisco/react-awesome-styled-grid#94]
The usage exmpales under https://awesome-styled-grid.netlify.com/usage which use a `style` property on `Row` or `Col` don't work as shown.

It fails with the error TS2322:
`(JSX attribute) style: {}
Type '{ children: Element; style: {}; }' is not assignable to type 'IntrinsicAttributes & IGridRowProps & { children?: ReactNode; }'.
  Property 'style' does not exist on type 'IntrinsicAttributes & IGridRowProps & { children?: ReactNode; }'.ts(2322)`

My setup:
typescript v3.8.3
react v16.12.0
styled-components v5.0.1

I can set styles to the FCs if I Style them with styled-components:

```typescript
const StyledRow = styled(Row)`
    height: 80px;
`;
```

This could be fixed by adding
`style?: React.CSSProperties;`
to the IGridRowProps in index.d.ts

**Comment by DJmRek** [comment]
I added pull request #95 to resolve this bug.

**Comment by eimerreis** [comment]
Waiting for this to be merged! @santosfrancisco

**Comment by santosfrancisco** [comment]
Sorry for the delay. Thanks for the contribution @DJmRek . Your PR has been merged.
