### ISSUE TITLE
TypeScript error

### ISSUE THREAD

**Issue by sorknes** [santosfrancisco/react-awesome-styled-grid#99]
I'm testing out your awesome grid system in a TypeScript project, but I'm getting this error:

```
ERROR in [at-loader] ./node_modules/react-awesome-styled-grid/types/index.d.ts:71:23 
    TS2314: Generic type 'CElement' requires 2 type argument(s).
```

The error is connect with these two:

```
export const Visible: React.CElement<IVisibleProps>;
export const Hidden: React.CElement<IHiddenProps>;
```

Is there a fix for this error?

**Comment by santosfrancisco** [comment]
@sorknes I'm sorry for answering so late! I'm working on it. Soon I will inform you of the progress.
